# Generated by Django 3.0.6 on 2022-01-20 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='GoogleCalendarTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('refresh_token', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
