# Generated by Django 3.0.6 on 2021-08-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_schoologytokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_schoology_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
