# Generated by Django 3.0.6 on 2021-09-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_is_schoology_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_schoology',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_schoology',
            field=models.BooleanField(default=False),
        ),
    ]
