# Generated by Django 3.0.6 on 2022-02-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220201_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='scheduled_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
