# Generated by Django 3.0.6 on 2021-09-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_assignment_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
