# Generated by Django 3.0.6 on 2021-11-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210930_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoologytokens',
            name='is_access',
            field=models.BooleanField(default=False),
        ),
    ]
