# Generated by Django 3.0.6 on 2022-05-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_assignment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=-8888, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='color',
            field=models.CharField(default='#808080', max_length=20),
        ),
    ]
