# Generated by Django 3.0.6 on 2022-06-03 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220519_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='scheduled_finish',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='scheduled_start',
        ),
        migrations.CreateModel(
            name='AssignmentSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_finish', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Assignment')),
            ],
        ),
    ]
