# Generated by Django 3.0.6 on 2022-06-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220603_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemeetingday',
            name='meeting_day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
