# Generated by Django 3.0.6 on 2022-06-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_schoologytoken_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='color',
            field=models.CharField(default='#C0392B', max_length=20),
        ),
    ]
