# Generated by Django 3.0.6 on 2022-06-24 02:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220624_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='color',
            field=models.CharField(default=api.models.assign_course_color, max_length=20),
        ),
    ]
