# Generated by Django 3.0.6 on 2022-06-28 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220628_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_phone_verified',
            new_name='verified',
        ),
    ]
