# Generated by Django 3.0.6 on 2022-08-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_applecalendarevents_applecalendarids'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_apple_calendar_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
