# Generated by Django 3.0.6 on 2022-08-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='estimated_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
